
# Firebase Cloud Messaging (FCM)

#use_frameworks!
#platform :ios, '8.0'


#pod 'Firebase/Core'
#pod 'Firebase/Messaging'

#target 'VietNamNewspapers' do
#end

source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '10.0'
use_frameworks!
pod 'Google-Mobile-Ads-SDK'
pod 'Firebase/Analytics'
pod 'Firebase/Core'
pod 'Firebase/Messaging'
pod 'Firebase/RemoteConfig'
#pod 'DJKFlipper'
pod 'ObjectMapper', '~> 3.5'


pod 'ImageLoader'

target 'VietNamNewspapers' do
end
